/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_facedetect_CustomJniFunc */

#ifndef _Included_com_example_administrator_facedetect_CustomJniFunc
#define _Included_com_example_administrator_facedetect_CustomJniFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_facedetect_CustomJniFunc
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_administrator_facedetect_CustomJniFunc_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     com_example_administrator_facedetect_CustomJniFunc
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_administrator_facedetect_CustomJniFunc_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_example_administrator_facedetect_CustomJniFunc
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_facedetect_CustomJniFunc_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_administrator_facedetect_CustomJniFunc
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_facedetect_CustomJniFunc_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_administrator_facedetect_CustomJniFunc
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_facedetect_CustomJniFunc_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_administrator_facedetect_CustomJniFunc
 * Method:    nativeSetFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_facedetect_CustomJniFunc_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_example_administrator_facedetect_CustomJniFunc
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_facedetect_CustomJniFunc_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
